name: CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # -------------------------
      # Backend Build (Spring Boot + Gradle)
      # -------------------------
      - name: Give permission to gradlew
        run: chmod +x Portfolio/Portfolio/gradlew

      - name: Build Backend with Gradle
        working-directory: Portfolio/Portfolio
        run: ./gradlew build

      # -------------------------
      # Frontend Build (React)
      # -------------------------
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Frontend Dependencies
        working-directory: Portfolio/myportfolio
        run: npm install

      - name: Build Frontend
        working-directory: Portfolio/myportfolio
        run: npm run build


